export const tweetsData = [
  {
    handle: `@EmilioDelgado`,
    profilePic: `descarga (7).jpg`,
    likes: 3830,
    retweets: 75,
    tweetText: `No, cariño, tú no eres fea; tú eres del montón.`,
    replies: [
      {
        handle: `@BelenLopezVazquez`,
        profilePic: `descarga (8).jpg`,
        tweetText: `¿Cómo del montón?`,
      },
      {
        handle: `@EmilioDelgado`,
        profilePic: `descarga (7).jpg`,
        tweetText: `O sea, del montón bueno. Porque hay un montón bueno y un montón malo. Pues tú eres del bueno. Luego está el montón que te cagas, pero esas están aparte. Además, ¿qué estoy diciendo? Si a mí lo que me gusta es una mujer inteligente... que tú tampoco lo eres, pero a mí me gustas.`,
      },
      {
        handle: `@BelenLopezVazquez`,
        profilePic: `descarga (8).jpg`,
        tweetText: `¿O sea que me estás llamando tonta?`,
      },
      {
        handle: `@EmilioDelgado`,
        profilePic: `descarga (7).jpg`,
        tweetText: `Sí... o sea, no, no, no, cariño. Una tía tonta era Alicia, que estaba más buena que tú, sí, pero era tonta. Y luego está Lucía, que también está más buena que tú y es más lista.`,
      },
      {
        handle: `@BelenLopezVazquez`,
        profilePic: `descarga (8).jpg`,
        tweetText: `¿Pero qué me estás diciendo? ¿Que te gusta Lucía?`,
      },
      {
        handle: `@EmilioDelgado`,
        profilePic: `descarga (7).jpg`,
        tweetText: `¡Noooo! Son ejemplos para que veas los tipos de mujeres que hay. Tú eres casi lista y casi guapa, o sea, del montón. Del montón bueno.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "016",
  },
  {
    handle: `@AmadorRivas 💎`,
    profilePic: `p1.webp`,
    likes: 320,
    retweets: 45,
    tweetText: `¡Que soy un tieso! Pero con clase, primo.`,
    replies: [
      {
        handle: `@AntonioRecio`,
        profilePic: `descarga.jpg`,
        tweetText: `¡Tieso y sin género!`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "001",
  },
  {
    handle: `@AntonioRecio`,
    profilePic: `descarga.jpg`,
    likes: 500,
    retweets: 90,
    tweetText: `Antonio Recio, mayorista no limpio pescado.`,
    replies: [
      {
        handle: `@Coque`,
        profilePic: `Coque_9.PNG.webp`,
        tweetText: `¿Y si te traigo un camión lleno de gambas?`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "002",
  },
  {
    handle: `@PaquitaSalas`,
    profilePic: `descarga (1).jpg`,
    likes: 850,
    retweets: 120,
    tweetText: `Cariño, hay que reinventarse o morir.`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "003",
  },
  {
    handle: `@Luisma`,
    profilePic: `descarga (2).jpg`,
    likes: 700,
    retweets: 110,
    tweetText: `Que el Luisma es tonto, el Luisma se ha metido de to y se ha quedao tonto...`,
    replies: [
      {
        handle: `@Barajas`,
        profilePic: `descarga (3).jpg`,
        tweetText: `Y yo soy su colega.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "004",
  },
  {
    handle: `@MauricioColmenero`,
    profilePic: `descarga (4).jpg`,
    likes: 650,
    retweets: 100,
    tweetText: `Aquí se viene a consumir, ¡coño ya!`,
    replies: [
      {
        handle: `@Chema`,
        profilePic: `descarga (5).jpg`,
        tweetText: `Mauricio, un poco de respeto.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "005",
  },
  {
    handle: `@RobertoAlonso`,
    profilePic: `descarga (6).jpg`,
    likes: 510,
    retweets: 95,
    tweetText: `¡Vamos, no me jodas!`,
    replies: [
      {
        handle: `@EmilioDelgado`,
        profilePic: `descarga (7).jpg`,
        tweetText: `Un poquito de por favor…`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "017",
  },
  {
    handle: `@BelenLopezVazquez`,
    profilePic: `descarga (8).jpg`,
    likes: 430,
    retweets: 75,
    tweetText: `¡Vete un poquito a la mierda!`,
    replies: [
      {
        handle: `@EmilioDelgado`,
        profilePic: `descarga (7).jpg`,
        tweetText: `Vale, pero con un poquito de por favor...`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "016",
  },
  {
    handle: `@FermínTrujillo`,
    profilePic: `descarga (9).jpg`,
    likes: 280,
    retweets: 55,
    tweetText: `¡Me cago en mi vida, Vicente!`,
    replies: [
      {
        handle: `@Vicente`,
        profilePic: `descarga (10).jpg`,
        tweetText: `Tranquilo, Fermín. Que hay Champions.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "008",
  },
  {
    handle: `@JudithBecker`,
    profilePic: `descarga (11).jpg`,
    likes: 360,
    retweets: 48,
    tweetText: `Hoy tengo terapia grupal. Se aceptan traumas.`,
    replies: [
      {
        handle: `@AmadorRivas`,
        profilePic: `p1.webp`,
        tweetText: `¡Merengue, merengue!`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "010",
  },
  {
    handle: `@DoñaFina`,
    profilePic: `descarga (12).jpg`,
    likes: 180,
    retweets: 30,
    tweetText: `¡Que os pincho!`,
    replies: [
      {
        handle: `@Coque`,
        profilePic: `Coque_9.PNG.webp`,
        tweetText: `Señora, guarde la aguja.`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "012",
  },
  {
    handle: `@Coque`,
    profilePic: `Coque_9.PNG.webp`,
    likes: 290,
    retweets: 45,
    tweetText: `Yo solo quería ser electricista, tío.`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "013",
  },
  {
    handle: `@JosemiCuesta`,
    profilePic: `descarga (13).jpg`,
    likes: 420,
    retweets: 80,
    tweetText: `Vale, pero tranquilito/a, ¿eh?`,
    replies: [
      {
        handle: `@JuanCuesta`,
        profilePic: `descarga (14).jpg`,
        tweetText: `Josemi, ¿tranquilito? ¡Si estoy que me salen chispas!`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "015",
  },
];
